# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/Transform.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Quaternion_pb2 as ros_dot_geometry__msgs_dot_Quaternion__pb2
from ros.geometry_msgs import Vector3_pb2 as ros_dot_geometry__msgs_dot_Vector3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ros/geometry_msgs/Transform.proto',
  package='ros.geometry_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n!ros/geometry_msgs/Transform.proto\x12\x11ros.geometry_msgs\x1a\"ros/geometry_msgs/Quaternion.proto\x1a\x1fros/geometry_msgs/Vector3.proto\"m\n\tTransform\x12/\n\x0btranslation\x18\x01 \x01(\x0b\x32\x1a.ros.geometry_msgs.Vector3\x12/\n\x08rotation\x18\x02 \x01(\x0b\x32\x1d.ros.geometry_msgs.Quaternionb\x06proto3'
  ,
  dependencies=[ros_dot_geometry__msgs_dot_Quaternion__pb2.DESCRIPTOR,ros_dot_geometry__msgs_dot_Vector3__pb2.DESCRIPTOR,])




_TRANSFORM = _descriptor.Descriptor(
  name='Transform',
  full_name='ros.geometry_msgs.Transform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='translation', full_name='ros.geometry_msgs.Transform.translation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='ros.geometry_msgs.Transform.rotation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=234,
)

_TRANSFORM.fields_by_name['translation'].message_type = ros_dot_geometry__msgs_dot_Vector3__pb2._VECTOR3
_TRANSFORM.fields_by_name['rotation'].message_type = ros_dot_geometry__msgs_dot_Quaternion__pb2._QUATERNION
DESCRIPTOR.message_types_by_name['Transform'] = _TRANSFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transform = _reflection.GeneratedProtocolMessageType('Transform', (_message.Message,), {
  'DESCRIPTOR' : _TRANSFORM,
  '__module__' : 'ros.geometry_msgs.Transform_pb2'
  # @@protoc_insertion_point(class_scope:ros.geometry_msgs.Transform)
  })
_sym_db.RegisterMessage(Transform)


# @@protoc_insertion_point(module_scope)
