# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/tf2_msgs/TFMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from datatypes.ros.geometry_msgs import TransformStamped_pb2 as ros_dot_geometry__msgs_dot_TransformStamped__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ros/tf2_msgs/TFMessage.proto',
  package='ros.tf2_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1cros/tf2_msgs/TFMessage.proto\x12\x0cros.tf2_msgs\x1a(ros/geometry_msgs/TransformStamped.proto\"D\n\tTFMessage\x12\x37\n\ntransforms\x18\x01 \x03(\x0b\x32#.ros.geometry_msgs.TransformStampedb\x06proto3'
  ,
  dependencies=[ros_dot_geometry__msgs_dot_TransformStamped__pb2.DESCRIPTOR,])




_TFMESSAGE = _descriptor.Descriptor(
  name='TFMessage',
  full_name='ros.tf2_msgs.TFMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transforms', full_name='ros.tf2_msgs.TFMessage.transforms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=156,
)

_TFMESSAGE.fields_by_name['transforms'].message_type = ros_dot_geometry__msgs_dot_TransformStamped__pb2._TRANSFORMSTAMPED
DESCRIPTOR.message_types_by_name['TFMessage'] = _TFMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TFMessage = _reflection.GeneratedProtocolMessageType('TFMessage', (_message.Message,), {
  'DESCRIPTOR' : _TFMESSAGE,
  '__module__' : 'ros.tf2_msgs.TFMessage_pb2'
  # @@protoc_insertion_point(class_scope:ros.tf2_msgs.TFMessage)
  })
_sym_db.RegisterMessage(TFMessage)


# @@protoc_insertion_point(module_scope)
