# Offender danger range
OFFENDER_DANGER_ZONE_LAT_NEAR = 0
OFFENDER_DANGER_ZONE_LAT_FAR = -5
OFFENDER_DANGER_ZONE_LONG_NEAR = -3
OFFENDER_DANGER_ZONE_LONG_FAR = 30

# Victim danger range
VICTIM_DANGER_ZONE_LAT_NEAR = 0
VICTIM_DANGER_ZONE_LAT_FAR = -5
VICTIM_DANGER_ZONE_LONG_NEAR = -3
VICTIM_DANGER_ZONE_LONG_FAR = 30
