# Offender danger range
# X axle
OFFENDER_DANGER_ZONE_LAT_NEAR = 0
OFFENDER_DANGER_ZONE_LAT_FAR = -10
# Y axle
OFFENDER_DANGER_ZONE_LONG_NEAR = -20
OFFENDER_DANGER_ZONE_LONG_FAR = 20

# Victim danger range
# X axle
VICTIM_DANGER_ZONE_LAT_NEAR = 3
VICTIM_DANGER_ZONE_LAT_FAR = -3
# Y axle
VICTIM_DANGER_ZONE_LONG_NEAR = -3
VICTIM_DANGER_ZONE_LONG_FAR = -6
