# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='coordinator.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x63oordinator.proto\x12\x02pb\"\x1e\n\x0b\x43oordinator\x12\x0f\n\x07warning\x18\x01 \x01(\x08\x62\x06proto3'
)




_COORDINATOR = _descriptor.Descriptor(
  name='Coordinator',
  full_name='pb.Coordinator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warning', full_name='pb.Coordinator.warning', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['Coordinator'] = _COORDINATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinator = _reflection.GeneratedProtocolMessageType('Coordinator', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATOR,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:pb.Coordinator)
  })
_sym_db.RegisterMessage(Coordinator)


# @@protoc_insertion_point(module_scope)
