# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guardian_angel.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guardian_angel.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14guardian_angel.proto\x12\x02pb\" \n\rGuardianAngel\x12\x0f\n\x07warning\x18\x01 \x01(\x08\x62\x06proto3'
)




_GUARDIANANGEL = _descriptor.Descriptor(
  name='GuardianAngel',
  full_name='pb.GuardianAngel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='warning', full_name='pb.GuardianAngel.warning', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['GuardianAngel'] = _GUARDIANANGEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GuardianAngel = _reflection.GeneratedProtocolMessageType('GuardianAngel', (_message.Message,), {
  'DESCRIPTOR' : _GUARDIANANGEL,
  '__module__' : 'guardian_angel_pb2'
  # @@protoc_insertion_point(class_scope:pb.GuardianAngel)
  })
_sym_db.RegisterMessage(GuardianAngel)


# @@protoc_insertion_point(module_scope)
