# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: victim_detector.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='victim_detector.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15victim_detector.proto\x12\x02pb\"\"\n\x0eVictimDetector\x12\x10\n\x08\x64\x65tected\x18\x01 \x01(\x08\x62\x06proto3'
)




_VICTIMDETECTOR = _descriptor.Descriptor(
  name='VictimDetector',
  full_name='pb.VictimDetector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detected', full_name='pb.VictimDetector.detected', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['VictimDetector'] = _VICTIMDETECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VictimDetector = _reflection.GeneratedProtocolMessageType('VictimDetector', (_message.Message,), {
  'DESCRIPTOR' : _VICTIMDETECTOR,
  '__module__' : 'victim_detector_pb2'
  # @@protoc_insertion_point(class_scope:pb.VictimDetector)
  })
_sym_db.RegisterMessage(VictimDetector)


# @@protoc_insertion_point(module_scope)
